# Generated by Django 5.2.7 on 2025-11-18 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('avail_dates_n_times', models.JSONField(blank=True, null=True)),
                ('about_restaurant', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fb_link', models.URLField(blank=True, null=True)),
                ('website_link', models.URLField(blank=True, null=True)),
                ('has_top_offers', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SeatingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('available_seats', models.IntegerField()),
                ('review', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReviewSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('five_star', models.PositiveIntegerField(default=0)),
                ('four_star', models.PositiveIntegerField(default=0)),
                ('three_star', models.PositiveIntegerField(default=0)),
                ('two_star', models.PositiveIntegerField(default=0)),
                ('one_star', models.PositiveIntegerField(default=0)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_summary', to='Reservations.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='seating_types',
            field=models.ManyToManyField(blank=True, to='Reservations.seatingtype'),
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='Amazing food and cozy atmosphere! The staff were friendly and attentive. Highly recommend for a great dining experience.')),
                ('creator_name', models.CharField(blank=True, default='Anonymous')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservations.restaurant')),
            ],
        ),
    ]
