# Generated by Django 5.2.7 on 2025-11-25 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurant_images/')),
                ('about_restaurant', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fb_link', models.URLField(blank=True, null=True)),
                ('website_link', models.URLField(blank=True, null=True)),
                ('has_top_offers', models.BooleanField(default=False)),
                ('default_opening_hour', models.IntegerField(default=18)),
                ('default_closing_hour', models.IntegerField(default=1)),
                ('slot_duration_minutes', models.IntegerField(default=60)),
                ('allow_advance_booking_days', models.IntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name='SeatingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_datetime', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservations.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('five_star', models.PositiveIntegerField(default=0)),
                ('four_star', models.PositiveIntegerField(default=0)),
                ('three_star', models.PositiveIntegerField(default=0)),
                ('two_star', models.PositiveIntegerField(default=0)),
                ('one_star', models.PositiveIntegerField(default=0)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_summary', to='Reservations.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantSeating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_seats', models.IntegerField(default=0)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservations.restaurant')),
                ('seating_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservations.seatingtype')),
            ],
            options={
                'unique_together': {('restaurant', 'seating_type')},
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='seating_types',
            field=models.ManyToManyField(blank=True, through='Reservations.RestaurantSeating', to='Reservations.seatingtype'),
        ),
        migrations.CreateModel(
            name='SpecialDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('closed_full_day', models.BooleanField(default=False)),
                ('adjusted_opening_hour', models.IntegerField(blank=True, null=True)),
                ('adjusted_closing_hour', models.IntegerField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservations.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='Amazing food and cozy atmosphere! The staff were friendly and attentive. Highly recommend for a great dining experience.')),
                ('creator_name', models.CharField(blank=True, default='Anonymous')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservations.restaurant')),
            ],
        ),
    ]
