# Generated by Django 5.2.7 on 2025-11-26 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='duration_minutes',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_end',
            field=models.CharField(default=5, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_no_of_seats',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_seatingtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Reservations.seatingtype'),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_start',
            field=models.CharField(default=5, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='card_number',
            field=models.IntegerField(default=3253),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='name_on_the_card',
            field=models.CharField(default='Abdullah', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantseating',
            name='price_per_seat',
            field=models.IntegerField(default=430),
        ),
        migrations.AddField(
            model_name='restaurantseating',
            name='total_seats',
            field=models.IntegerField(default=10),
        ),
    ]
