# Generated by Django 5.2.7 on 2025-11-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0002_remove_booking_duration_minutes_booking_booking_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_datetime',
            field=models.DateField(),
        ),
    ]
