# Generated by Django 5.2.7 on 2025-11-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0003_alter_booking_booking_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_datetime',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_end',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_start',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_end_dateTime',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_start_dateTime',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
