# Generated by Django 5.2.7 on 2026-01-04 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0006_reviewsummary_points_userprofile_favouriterestaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='seating_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Reservations.restaurantseating'),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='card_number',
            field=models.CharField(max_length=16),
        ),
    ]
