# Generated by Django 5.2.7 on 2026-01-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0008_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(default='Karachi', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cool_down',
            field=models.IntegerField(default=30),
        ),
    ]
