# Generated by Django 5.2.7 on 2026-01-05 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0009_restaurant_city_restaurant_cool_down'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantseating',
            old_name='available_seats',
            new_name='available_tables',
        ),
        migrations.RenameField(
            model_name='restaurantseating',
            old_name='price_per_seat',
            new_name='price_per_table',
        ),
        migrations.RenameField(
            model_name='restaurantseating',
            old_name='total_seats',
            new_name='total_tables',
        ),
    ]
