# Generated by Django 5.2.7 on 2026-01-07 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0010_rename_available_seats_restaurantseating_available_tables_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteSeating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_seatings', to='Reservations.restaurant')),
                ('seating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by', to='Reservations.restaurantseating')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_seatings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'seating'), name='unique_user_seating')],
            },
        ),
    ]
