# Generated by Django 5.2.7 on 2026-01-07 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0011_favouriteseating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavouriteSeating',
        ),
    ]
